# This is a basic workflow to help you get started with Actions

name: Have some fun with EESSI in GitHub Actions

# when
on:
  push:
    branches:
      - main

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: eessi/github-action-eessi@v1
    - name: Test EESSI
      run: |
        module avail
      shell: bash
